config/routes.rb
Reservoir::Application.routes.draw do
  
  get '/rooms/remote/calendar/update', :to => "rooms#start_remotecal_worker", :as => "remote_calendar_update"
  resources :rooms do
    get "/reservations/remote", :to => "reservations#index_remote"
    post "/reservations/deletemany", :to => "reservations#destroymany"
    get "/remote/calendar/update", :to => "rooms#start_remotecal_worker", :as => "remote_calendar_update"
    resources :reservations 
  end
 
  devise_for :users, controllers: { registrations: "registrations" }
  devise_scope :user  do
    get '/login', :to => 'devise/sessions#new', :as => "login"
    get '/register', :to => 'devise/registrations#new', :as => "register"
    get '/users/edit/password', :to => 'registrations#edit_password', :as => "user_password_change"
    get '/users/show/:id', :to => "registrations#show", :as => "user"   
  end

  get '/users/show/:id/reservations', :to => "reservations#indexByUser", :as => "user_reservations"
  get '/reservations/find', :to => "reservations#find"
  post '/reservations/find', :to => "reservations#search"
  post '/search', :to => "home#search", :as => "search"
  
  
  
  root :to => "home#index"

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  DATETIME_FORMAT = Time::DATE_FORMATS[:date_time_nosec]
  
  def index
    @search = Reservation.new(start_string: Time.now.to_s(:date_time_nosec), end_string: (Time.now + 30.minutes).to_s(:date_time_nosec)) if !defined?(@search)
    
    now = Time.zone.now
    @reservations_running = Reservation.all_occurrences(Reservation.between(now, now), after: now, until: now)
    @reservations_running.concat(TempReservation.all_occurrences(TempReservation.between(now, now), after: now, until: now))
    @reservations_running.sort_by! {|res| res.start }
    @reservations_running = @reservations_running.take(10)
    
    if(@reservations_running.empty?)
      @free_rooms = Room.all
    else
      @free_rooms = Room.where("id NOT IN (?)", @reservations_running.map(&:room_id)).order("name ASC")
    end
  end
  
  def search
    error = false
    begin
      @search = Reservation.new(params[:reservation])
      @search.start = Time.zone.at((DateTime.strptime(params[:reservation][:start_string], DATETIME_FORMAT) - DateTime.local_offset).to_i)
      @search.end = Time.zone.at((DateTime.strptime(params[:reservation][:end_string], DATETIME_FORMAT) - DateTime.local_offset).to_i)
      error = !@search.valid?
    rescue ArgumentError
      @search.errors.add(:start_string,"")
      @search.errors.add(:end_string,"")
      error = true
    end
    
    if error
      index
      render action: "index"
    else
      
      reservations = Reservation.all_occurrences(Reservation.between(@search.start,@search.end), after: @search.start, until: @search.end)
      reservations.concat(TempReservation.all_occurrences(TempReservation.between(@search.start,@search.end), after: @search.start, until: @search.end))
      occupied_rooms_ids = reservations.map(&:room_id).uniq
      
      if(occupied_rooms_ids.empty?)
        @rooms = Room.all
      else
        @rooms = Room.where("id NOT IN (?)", occupied_rooms_ids)
      end
      
      respond_to do |format|
        format.html
        format.json { render json: @rooms }
      end
     
    end
   
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.haml
-@sidelinks = {glyph("search") + "Find a free room" => "#findroom", glyph("star") + "Free rooms" => "#freerooms",  glyph("play-circle") + "Running reservations" => "#running"}
-@spy = true

.page-header
  %h1 Welcome to Reservoir
  
#findroom
  %h2 Find a free room
  .well{style: "width: 60%"}
    = form_for(@search, url: search_path, html: { class: "form-inline"}) do |f|
      %p
        = glyph("search")
        %strong Enter desired date and time of reservation
      = f.hidden_field :summary, value: "search"
      = f.text_field :start_string, placeholder: "start time", class: "input-medium"
      &nbsp;to&nbsp;
      = f.text_field :end_string, placeholder: "end time", class: "input-medium"
      = f.submit" Find me a room!", class: "btn btn-primary"

#freerooms
  %h2 Free rooms
  = mute(@free_rooms, "no room available") do
    %table.table.table-striped.table-hover
      %thead
        %tr
          %th Name
          %th Capacity
          %th Location
          %th Equipment
      %tbody
        -@free_rooms.each do |room|
          %tr
            %td= link_to(room.name, room_path(room))
            %td
              %span.badge.badge-info= room.capacity
            %td= mute(room.location)
            %td= mute(room.equipment)       

#running
  %h2 Running reservations
  = mute(@reservations_running, "no reservation is running") do
    %table.table.table-striped.table-hover
      %thead
        %tr
          %th Summary
          %th Room
          %th Author
          %th Start
          %th End
          %th Description
      %tbody
        - @reservations_running.each do |res|
          %tr{class: (res.type==:remote)? "success" : ""}
            %td= link_to res.summary, "#reservationModal" + res.sid, data: {toggle: "modal"} 
            %td= link_to res.room.name, room_path(res.room)
            %td= mute(res.author, "none") { link_to res.author.login, user_path(res.author) }
            %td= res.start.localtime.to_s :date_time_nosec
            %td= res.end.localtime.to_s :date_time_nosec
            %td= cutlong(res.description, 50)
            
    -@reservations_running.uniq {|res| res.id }.each do |res|
      = render partial: "reservations/modal", locals: {reservation: res, show_room: true}
     

  
            

app/views/home/search.html.haml
.page-header
  %h2
    Search
    %blockquote
      %p.muted
        from 
        = params[:reservation][:start_string]
        to 
        = params[:reservation][:end_string]
      
      
%table.table
  %thead
    %tr
      %th Name
      %th Capacity
      %th Location
      %th Equipment
        
  %tbody
    - @rooms.each do |room|
      %tr
        %td= link_to room.name, room_path(room)
        %td
          .badge.badge-info= room.capacity
        %td= mute(room.location)
        %td= mute(room.equipment)