config/routes.rb
Reservoir::Application.routes.draw do
  
  get '/rooms/remote/calendar/update', :to => "rooms#start_remotecal_worker", :as => "remote_calendar_update"
  resources :rooms do
    get "/reservations/remote", :to => "reservations#index_remote"
    post "/reservations/deletemany", :to => "reservations#destroymany"
    get "/remote/calendar/update", :to => "rooms#start_remotecal_worker", :as => "remote_calendar_update"
    resources :reservations 
  end
 
  devise_for :users, controllers: { registrations: "registrations" }
  devise_scope :user  do
    get '/login', :to => 'devise/sessions#new', :as => "login"
    get '/register', :to => 'devise/registrations#new', :as => "register"
    get '/users/edit/password', :to => 'registrations#edit_password', :as => "user_password_change"
    get '/users/show/:id', :to => "registrations#show", :as => "user"   
  end

  get '/users/show/:id/reservations', :to => "reservations#indexByUser", :as => "user_reservations"
  get '/reservations/find', :to => "reservations#find"
  post '/reservations/find', :to => "reservations#search"
  post '/search', :to => "home#search", :as => "search"
  
  
  
  root :to => "home#index"

end

app/models/reservation.rb
class Reservation < ActiveRecord::Base

  include ReservationModule
  

  belongs_to :room
  belongs_to :author, :class_name => "User"
  attr_accessible :description, :end, :start, :summary, :scheduleyaml, :start_string, :end_string
  attr_accessor :start_string, :end_string, :schedule

  validates :summary, :presence => true, :length => {:maximum => 150}
  validates :start_string, presence: true
  validates :end_string, presence: true
  validate :start_before_end
  def start_before_end
    if start && self.end &&  start >= self.end
      errors.add(:start_string, "must be before end")
      errors.add(:end_string, "must be after start")
    end
  end

  scope :between, lambda {|start,end_date| where("(\"end\" >= ? AND \"start\" <= ?) OR (scheduleyaml IS NOT NULL)", start.utc, end_date.utc) }
  scope :of, lambda {|room| where(:room_id => room.id)}
  scope :after, lambda {|start_time| where("(\"end\" >= ?) OR (scheduleyaml IS NOT NULL)", Reservation.format_date(start_time))}
  scope :before, lambda {|end_time| where("(\"start\" < ?)", Reservation.format_date(end_time))}

  def self.format_date(date_time)
    Time.at(date_time.to_i).utc.to_formatted_s(:db)
  end

  def sid
    "native" + id.to_s
  end

  def type
    :native
  end
  
  #callbacks
  before_save do
    if(@schedule)
      self.scheduleyaml = @schedule.to_yaml
    else
      self.scheduleyaml = nil
    end 
  end
  
  after_initialize do
    if(self.scheduleyaml)
      @schedule = Schedule.from_yaml(self.scheduleyaml)
    end
  end
  
def as_json(options = {})
    {
      :id => self.id,
      :title => self.summary,
      :description => self.description,
      :start => self.start.localtime.rfc822,
      :end => self.end.localtime.rfc822,
      :recurrence => (self.recurs? ? self.schedule.to_s : nil),
      :allDay => false,
      :room => (self.room ? self.room.as_json : "" ),
      :author => self.author.as_json,
      :url => (self.id ? Rails.application.routes.url_helpers.room_reservation_path(self.room, self) : ""),
      :type => "native"
    }
  end
  
  def as_public_json
    {
      :title => self.summary,
      :description => self.description,
      :start => self.start.rfc822,
      :end => self.end.rfc822,
      :allDay => false,
      :room_id => self.room.id,
      :author_id => self.author.id,
      :type => "native"
    }
  end
end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
  before_filter :authenticate_user!, except: [:index, :show, :indexByUser, :find, :search, :index_remote]
  DATETIME_FORMAT = Time::DATE_FORMATS[:date_time_nosec]
  layout "wide", only: [:search]
  
  def index
    @room = Room.find(params[:room_id])
    @reservations = Reservation.of(@room).order("\"start\" ASC")
    
    @reservations = @reservations.after(params[:start]) if params[:start]
    @reservations = @reservations.before(params[:end]) if params[:end]
    
    #retrieve events from calendar url
    if(params[:start]) then params[:after] = Time.zone.at(params[:start].to_i) end
    if(params[:end]) then params[:until] = Time.zone.at(params[:end].to_i) end
    @reservations = Reservation.all_occurrences(@reservations, params)
    
    respond_to do |format|
      format.html { redirect_to @room }
      format.js { render :json => @reservations }
      format.json { render :json => @reservations.map { |r| r.as_public_json } }
    end
  end
  
  def index_remote
    @room = Room.find(params[:room_id])
    @reservations = TempReservation.of(@room)
    
    @reservations = @reservations.after(params[:start]) if params[:start]
    @reservations = @reservations.before(params[:end]) if params[:end]
    
   
    if(params[:start]) then params[:after] = Time.zone.at(params[:start].to_i) end
    if(params[:end]) then params[:until] = Time.zone.at(params[:end].to_i) end
    @reservations = TempReservation.all_occurrences(@reservations, params)
    
    
    respond_to do |format|
      format.js { render :json => @reservations }
    end
  end
  
  def indexByUser
    @user = User.find(params[:id])
    
    
     respond_to do |format|
      format.html
      format.js do
        @reservations = Reservation.where(author_id: @user.id).order("\"start\" ASC")

        @reservations = @reservations.after(params[:start]) if params[:start]
        @reservations = @reservations.before(params[:end]) if params[:end]

        if(params[:start]) then params[:after] = Time.zone.at(params[:start].to_i) end
        if(params[:end]) then params[:until] = Time.zone.at(params[:end].to_i) end
        @reservations = Reservation.all_occurrences(@reservations, params)

        render :json => @reservations
      end
      format.json do
        @reservations = Reservation.where(author_id: @user.id).order("\"start\" ASC")

        @reservations = @reservations.after(params[:start]) if params[:start]
        @reservations = @reservations.before(params[:end]) if params[:end]
        
        render :json => @reservations.map { |r| r.as_public_json }
      end 
    end
  end
  
  # mostly as fallback when JS is not allowed
  # TODO: what to do with TempReservations?
  def show
    @reservation = Reservation.find(params[:id])
    
    respond_to do |format|
      format.html
      format.js { render :json => @reservation }
      format.json { render :json => @reservation.as_public_json }
    end
  end
   
  # TODO: Implement recursion!
  def create
    @room = Room.find(params[:room_id])
    
    error = false
    begin
      @reservation = Reservation.new(params[:reservation])
      @reservation.room = @room
      @reservation.author = current_user
      @reservation.start = Time.zone.at(DateTime.strptime(params[:reservation][:start_string], DATETIME_FORMAT).to_i)
      @reservation.end = Time.zone.at(DateTime.strptime(params[:reservation][:end_string], DATETIME_FORMAT).to_i)
      @reservation.start -= @reservation.start.localtime.utc_offset
      @reservation.end -= @reservation.end.localtime.utc_offset
      
      
      @reservation.schedule = build_schedule(@reservation.start, @reservation.end, params)
        
        
      error = !@reservation.save
    rescue ArgumentError
      @reservation.errors.add(:start_string, "")
      @reservation.errors.add(:end_string, "")
      error = true
    end
    
    if error
      render action: "new"
    else
      flash[:notice] = "Reservation #{@reservation.summary.html_safe} was created!"
      redirect_to @room
    end
  end
  
  def new
    @room = Room.find params[:room_id]
    @reservation = Reservation.new
  end
  
 
  def destroy
    reservation = Reservation.find(params[:id])
    
    reservation.destroy
    
    redirect_to reservation.room
    flash[:notice] = "Reservation #{reservation.summary.html_safe} was deleted!"
  end
  
  def destroymany
    @room = Room.find(params[:room_id])
    ids = params[:deleteids].keys
    deleted = []
    
    ids.each do |id|
      reservation = Reservation.find(id)
      reservation.destroy
      
      deleted << reservation.summary
    end
    
    redirect_to room_reservations_path(@room)
    flash[:notice] = "The following reservations were deleted: " + deleted.map() { |text| text.html_safe }.join(", ")
  end
  
  def edit
    @room = Room.find(params[:room_id])
    @reservation = Reservation.find(params[:id])
    @reservation.start_string = @reservation.start.localtime.strftime(DATETIME_FORMAT)
    @reservation.end_string = @reservation.end.localtime.strftime(DATETIME_FORMAT)
    
    #owner
    if(@reservation.author==current_user)
      params[:assign_to_me] = "1"
    end
    
    #recurrence options
    if(@reservation.recurs?)
      rule = @reservation.schedule.rrules.first
      params[:interval] = rule.to_hash[:interval].to_s
      
      #frequency
      if(rule.is_a? IceCube::DailyRule)
        params[:frequency] = "1"
      elsif(rule.is_a? IceCube::WeeklyRule)
        params[:frequency] = "2"
        if(rule.to_hash[:validations] && rule.to_hash[:validations][:day])
          params[:weekday] = rule.to_hash[:validations][:day].map(&:to_s)
        end
      elsif(rule.is_a? IceCube::MonthlyRule)
        params[:frequency] = "3"
      elsif(rule.is_a? IceCube::YearlyRule)
        params[:frequency] = "4"
        if(rule.to_hash[:validations] && rule.to_hash[:validations][:month_of_year])
          params[:yearmonths] = rule.to_hash[:validations][:month_of_year].map(&:to_s) 
        end
      end
    
      #until, count
      if(rule.until_time)
        params[:endtype] = "1"
        params[:until] =  rule.until_time.to_s :date_time_nosec
      elsif(rule.occurrence_count)
        params[:endtype] = "2"
        params[:maxcount] = rule.occurrence_count.to_s
      end
    end
    
  end
  
  # TODO: revise recurrence
  def update
    @room = Room.find(params[:room_id])
    error = false
    
    begin
      @reservation = Reservation.find(params[:id])
      @reservation.assign_attributes(params[:reservation])
      @reservation.author = current_user if params[:assign_to_me]
      @reservation.start = Time.zone.at(DateTime.strptime(params[:reservation][:start_string], DATETIME_FORMAT).to_i)
      @reservation.end = Time.zone.at(DateTime.strptime(params[:reservation][:end_string], DATETIME_FORMAT).to_i)
      @reservation.start -= @reservation.start.localtime.utc_offset
      @reservation.end -= @reservation.end.localtime.utc_offset
      
      
      #recurrence
      @reservation.schedule = build_schedule(@reservation.start, @reservation.end, params)
      
      error = !@reservation.save
    rescue ArgumentError
      @reservation.errors.add(:start_string,"")
      @reservation.errors.add(:end_string,"")
      error = true
    end
    
    if error
      render action: "edit"
    else
      flash[:notice] = "Reservation #{@reservation.summary.html_safe} was updated!"
      redirect_to @reservation.room
    end
  end
  
  def find
    @reservation = Reservation.new
    @rooms = Room.all.insert(0, Room.new(name: "--no particular room--", id: nil))
  end
  
  def search
    room = params[:reservation].delete(:room)
    @reservation = Reservation.new(params[:reservation])
    search = @reservation
    search.room_id = room
    
    if search.summary.empty? && search.start_string.empty? && search.end_string.empty? && search.description.empty?
      flash[:error] = "Enter some search parameters first!"
      
      @rooms = Room.all.insert(0, Room.new(name: "--no particular room--", id: nil))
      render action: "find"
    else
      begin
        search.start = Time.zone.at((DateTime.strptime(params[:reservation][:start_string], DATETIME_FORMAT) - DateTime.local_offset - 1.minute).to_i) unless search.start_string.empty?
        search.end = Time.zone.at((DateTime.strptime(params[:reservation][:end_string], DATETIME_FORMAT) - DateTime.local_offset + 1.minute).to_i) unless search.end_string.empty?
       
        if search.start_string.empty? || search.end_string.empty? || (search.start <= search.end)
          @reservations = Reservation.order("\"start\" ASC")
        
          @reservations = @reservations.where("LOWER(summary) LIKE LOWER(?)", '%' + search.summary + '%') unless search.summary.empty?
          @reservations = @reservations.where("LOWER(description) LIKE LOWER(?)", '%' + search.description + '%') unless search.description.empty?
          @reservations = @reservations.after(search.start.to_i) unless search.start_string.empty?
          @reservations = @reservations.before(search.end.to_i) unless search.end_string.empty?
          @reservations = @reservations.where("room_id = ?", search.room_id) unless search.room_id == nil
          
          @temps = TempReservation.order("\"start\" ASC")
          @temps = @temps.where("LOWER(summary) LIKE LOWER(?)", '%' + search.summary + '%') unless search.summary.empty?
          @temps = @temps.where("LOWER(description) LIKE LOWER(?)", '%' + search.description + '%') unless search.description.empty?
          @temps = @temps.after(search.start.to_i) unless search.start_string.empty?
          @temps = @temps.before(search.end.to_i) unless search.end_string.empty?
          @temps = @temps.where("room_id = ?", search.room_id) unless search.room_id == nil
          
          @reservations.concat(@temps)
          
          unless(search.start_string.empty?)
            unless(search.end_string.empty?)

app/helpers/reservations_helper.rb
module ReservationsHelper
  
  def reservation_class(reservation)
    if reservation.end.localtime < Time.now
      "pastevent"
    end
  end
  
  
  
end

app/views/reservations/_form.html.haml
-if @reservation.errors.any?
  .alert.alert-error.fade.in
    Some #{@reservation.errors.size==1? "error" : "errors"} occured, fix #{@reservation.errors.size==1? "it" : "them"} and try again.
    

-if !(defined? url) then url = room_reservations_path(@room) end

= form_for(@reservation, url: url, html: {class: "form-horizontal"}) do |f|
  .pull-right.span4
    .accordion#recurrence.inputs-small
      .accordion-group
        .accordion-heading
          %a.accordion-toggle{"data-toggle" => "collapse", "data-parent" => "recurrence", href: "#recOptions"}
            Recurrence options
        .accordion-body.collapse#recOptions{class: (params[:frequency] && params[:frequency]!="0" ? "in" : "")}
          .accordion-inner
            repeat every 
            = text_field_tag("interval", params[:interval], class: "input-mini")
            %select.input-small#freqSelect{name: "frequency", value: (params[:frequency])}
              %option{value: 0, (params[:frequency]=="0" ? "selected" : "") => ""}
                never
              %option{value: 1, (params[:frequency]=="1" ? "selected" : "") => ""}
                days
              %option{value: 2, (params[:frequency]=="2" ? "selected" : "") => ""}
                weeks
              %option{value: 3, (params[:frequency]=="3" ? "selected" : "") => ""}
                months
              %option{value: 4, (params[:frequency]=="4" ? "selected" : "") => ""}
                years
            
            %br
            .well.well-small#weeklyoptions{style: (params[:frequency]=="2" ? "" : "display:none;")}
              %input{type: "checkbox", name: "weekday[]", value: 1, checked: (params[:weekday] && params[:weekday].include?("1"))} Mo
              %input{type: "checkbox", name: "weekday[]", value: 2, checked: (params[:weekday] && params[:weekday].include?("2"))} Tu
              %input{type: "checkbox", name: "weekday[]", value: 3, checked: (params[:weekday] && params[:weekday].include?("3"))} We
              %input{type: "checkbox", name: "weekday[]", value: 4, checked: (params[:weekday] && params[:weekday].include?("4"))} Th
              %input{type: "checkbox", name: "weekday[]", value: 5, checked: (params[:weekday] && params[:weekday].include?("5"))} Fr
              %input{type: "checkbox", name: "weekday[]", value: 6, checked: (params[:weekday] && params[:weekday].include?("6"))} Sa
              %input{type: "checkbox", name: "weekday[]", value: 0, checked: (params[:weekday] && params[:weekday].include?("0"))} Su
            %br
            .well.well-small#yearlyoptions{style: (params[:frequency]=="4" ? "" : "display:none;")}
              %select{name: "yearmonths[]", multiple: true}
                %option{value: 1, (params[:yearmonths] && params[:yearmonths].include?("1") ? "selected" : "") => ""} January
                %option{value: 2, (params[:yearmonths] && params[:yearmonths].include?("2") ? "selected" : "") => ""} February
                %option{value: 3, (params[:yearmonths] && params[:yearmonths].include?("3") ? "selected" : "") => ""} March
                %option{value: 4, (params[:yearmonths] && params[:yearmonths].include?("4") ? "selected" : "") => ""} April
                %option{value: 5, (params[:yearmonths] && params[:yearmonths].include?("5") ? "selected" : "") => ""} May
                %option{value: 6, (params[:yearmonths] && params[:yearmonths].include?("6") ? "selected" : "") => ""} June
                %option{value: 7, (params[:yearmonths] && params[:yearmonths].include?("7") ? "selected" : "") => ""} July
                %option{value: 8, (params[:yearmonths] && params[:yearmonths].include?("8") ? "selected" : "") => ""} August
                %option{value: 9, (params[:yearmonths] && params[:yearmonths].include?("9") ? "selected" : "") => ""} September
                %option{value: 10, (params[:yearmonths] && params[:yearmonths].include?("10") ? "selected" : "") => ""} October
                %option{value: 11, (params[:yearmonths] && params[:yearmonths].include?("11") ? "selected" : "") => ""} November
                %option{value: 12, (params[:yearmonths] && params[:yearmonths].include?("12") ? "selected" : "") => ""} December
            
            %br
            
            
            %input{type: "radio", name: "endtype", value: 0, checked: (!params[:endtype] || params[:endtype]=="0")}
              forever
            %br
            
            %input{type: "radio", name: "endtype", value: 1, checked: params[:endtype] == "1"}
              until 
              %input#untilField{type: "text", name: "until", value: params[:until]}
            %br
            
            %input{type: "radio", name: "endtype", value: 2, checked: params[:endtype] == "2"}
              maximum occurrences 
              %input.input-mini{type: "text", name: "maxcount", value: params[:maxcount]}
                  
      


  .control-group
    = f.label :summary, class: "control-label"
    .controls
      = f.text_field :summary, placeholder: "summary"
      -unless @reservation.errors[:summary].empty?
        %p.text-error-inline= @reservation.errors[:summary].join(", ")
  
  .control-group
    = f.label :start_string, "Start", class: "control-label"
    .controls
      = f.text_field :start_string, placeholder: "start date and time"
      -unless @reservation.errors[:start_string].empty?
        %p.text-error-inline= @reservation.errors[:start_string].join(", ")
        
  
  .control-group
    = f.label :end_string, "End", class: "control-label"
    .controls
      = f.text_field :end_string, placeholder: "end date and time"
      -unless @reservation.errors[:end_string].empty?
        %p.text-error-inline= @reservation.errors[:end_string].join(", ")
      
  .control-group
    = f.label :description, class: "control-label"
    .controls
      = f.text_area :description, rows: "10"
      -unless @reservation.errors[:description].empty?
        %p.text-error-inline= @reservation.errors[:description].join(", ")
  -if params[:action]=="edit"
    .control-group
      = f.label :assign_to_me, "Make me owner", class: "control-label"
      .controls
        %input{type: "checkbox", name: "assign_to_me", value: 1, checked: (params[:assign_to_me] && params[:assign_to_me]=="1")}
        
  
  
  .form-actions
    = f.submit params[:action]=="edit"? "Update" : "Create", class: "btn btn-primary"
    = link_to "Back", :back, class: "btn"

app/views/reservations/_modal.html.haml
.modal.hide.fade{id: "reservationModal" + (defined?(reservation)? reservation.sid : "") ,role: "dialog", "aria-labelledby" => "reservationLabel", "aria-hidden" => "true"}
  .modal-header
    %button.close{type: "button", "data-dismiss" => "modal", "aria-hidden" => "true"} &times;
    %h3#reservationLabel
      -if defined?(reservation)
        = reservation.summary
  .modal-body
    %table.table.table-bordered
      %tbody
        -unless defined?(hide_author) && hide_author
          %tr
            %td
              %strong Author
            %td#authorField
              - if defined?(reservation)
                = mute(reservation.author) do
                  = link_to reservation.author.login, user_path(reservation.author)
                  
        -if defined?(show_room) && show_room
          %tr
            %td
              %strong Room
            %td#roomField
              - if defined?(reservation)
                = link_to reservation.room.name, room_path(reservation.room)
        %tr
          %td
            %strong Start
          %td#startField
            -if defined?(reservation)
              = reservation.start.to_s :date_time_nosec
        %tr
          %td
            %strong End
          %td#endField
            -if defined?(reservation)
              = reservation.end.to_s :date_time_nosec
        %tr
          %td
            %strong Recurrence
          %td#recField
            - if (defined?(reservation))
              = mute(reservation.recurs?, "no recurrence") do
                = reservation.schedule.to_s
    %h4 Description:
    %blockquote
      %p#descriptionField
        -if defined?(reservation)
          = reservation.description
  .modal-footer
    .btn-group
      -if user_signed_in?
        %a.btn#editLink{href: (defined?(reservation)? edit_room_reservation_path(reservation.room, reservation): "#"), style: ((defined?(reservation) && reservation.type == :remote)? "display:none" : "")}
          = glyph("cog")
          Edit
        %a.btn.btn-danger#deleteLink{"data-confirm" => "Are you sure?", "data-method" => "delete", href: (defined?(reservation)? room_reservation_path(reservation.room, reservation) : "#"), style: ((defined?(reservation) && reservation.type == :remote)? "display:none" : "")}
          = glyph "remove"
          Delete
      %button.btn.btn-primary{type: "button", "data-dismiss" => "modal", "aria-hidden" => "true"} Close
          

app/views/reservations/edit.html.haml
.page-header
  %h1 
    Edit reservation
    %small= @room.name

= render "form", url: room_reservation_path(@room, @reservation)

app/views/reservations/find.html.haml
.page-header
  %h2 Find a reservation
  
= form_for(@reservation, url: reservations_find_path, method: "post", html: { class: "form-horizontal" }) do |f|
  .control-group
    = f.label :summary, "Summary contains", class: "control-label"
    .controls
      = f.text_field :summary, placeholder: "summary fraction"
      
  .control-group
    = f.label :room, class: "control-label"
    .controls
      = f.collection_select :room, @rooms, :id, :name
      
  .control-group
    = f.label :start_string, "Starts after", class: "control-label"
    .controls
      = f.text_field :start_string
      -unless @reservation.errors[:start_string].empty?
        %p.text-error-inline= @reservation.errors[:start_string].join(", ")
      
  .control-group
    = f.label :end_string, "Ends before", class: "control-label"
    .controls
      = f.text_field :end_string
      -unless @reservation.errors[:end_string].empty?
        %p.text-error-inline= @reservation.errors[:end_string].join(", ")
      
  .control-group
    = f.label :description, "Description contains", class: "control-label"
    .controls
      = f.text_area :description, placeholder: "description fraction", rows: "3"

  .form-actions
    = f.submit "Search", class: "btn btn-primary"

app/views/reservations/index.html.haml
-content_for :script do
  :javascript
    var reservationsFeed = "#{room_reservations_path(@room)}.js"

.page-header
  %h2
    Reservations 
    %small= @room.name
  

  
%ul.nav.nav-tabs
  %li
    %a{href: "#list", data: {toggle: "tab"}} List view
  %li.active
    %a{href: "#calendar-tab", data: {toggle: "tab"}} Calendar view
    
.tab-content
  .tab-pane#list
    = form_tag(room_reservations_deletemany_path(@room)) do |f|
      %table.table.table-striped.table-hover
        %thead
          %tr
            %th Summary
            %th Author
            %th Start
            %th End
            %th Description
        %tbody
          - @reservations.each do |res|
            %tr
              %td
                
                %input.manyinput{type: "checkbox", name: "deleteids[#{res.id}]", value: "1", style: "display: none", class: reservation_class(res)}
                = res.summary
              %td= mute(res.author, "none") { link_to(res.author.login, user_path(res.author)) }
              %td= res.start.localtime.to_s :date_time_nosec
              %td= res.end.localtime.to_s :date_time_nosec
              %td= cutlong(res.description, 40)
              -if user_signed_in?
                %td
                  .btn-group
                    = link_to content_tag(:span,'', class: "icon-cog") + " Edit", edit_room_reservation_path(@room, res), class: "btn btn-small"
                    = link_to content_tag(:span,'', class: "icon-remove") + " Delete", room_reservation_path(@room, res), method: :delete, class:"btn btn-danger btn-small", data: {confirm: "Are you sure?"}
      
      -if user_signed_in?
        %a.btn#manyswitch{href: "#"} Select many
        .form-actions#manyaction{style: "display: none;"}
          %input.btn.btn-danger{type: "submit", value: "Delete all selected"}
          %a.btn.btn-info#selectpast Select reservations in the past
          .pull-right
            %a.close#manyclose{href: "#"} &times;
    
      
            
  .tab-pane.active#calendar-tab
    #calendar
    
= render "modal"

app/views/reservations/indexByUser.html.haml
-content_for :script do
  :javascript
    var reservationsFeeds = ["#{user_reservations_path(@user)}.js"];

.page-header
  %h1
    Reservations
    %small= @user.login

#calendar

= render( partial: "reservations/modal", locals: { show_room: true, hide_author: true })

app/views/reservations/new.html.haml
.page-header
  %h1
    New reservation
    %small= @room.name

= render "form"

app/views/reservations/search.html.haml
.page-header
  %h2
    Reservation search
    %br
  %blockquote
    %p
      = mute(@reservation.summary.empty?, "summary contains '#{@reservation.summary}'") { "" }
    %p.muted
      = mute(@reservation.room_id != nil, "") { "from room '#{@reservation.room.name}'" }
    %p
      = mute(@reservation.start_string.empty?, "starts after '#{@reservation.start_string}'") { "" }
    %p
      = mute(@reservation.end_string.empty?, "ends before '#{@reservation.end_string}'") { "" }
    %p
      = mute(@reservation.description.empty?, "description contains '#{@reservation.description}'") { "" }

= mute(@reservations, "none reservations found") do     
  %table.table
    %thead
      %tr
        %th Summary
        %th Room
        %th Author
        %th Start
        %th End
        %th Recurrence
        %th Description
    %tbody
      -@reservations.each do |res|
        %tr{class: (res.type==:remote ? "success" : "")}
          %td= link_to(res.summary, "#reservationModal" + res.sid, data: { toggle: "modal" })
          %td= link_to(res.room.name, room_path(res.room))
          %td= mute(res.author) { link_to(res.author.login, user_path(res.author)) }
          %td= res.start.localtime.to_s :date_time_nosec
          %td= res.end.localtime.to_s :date_time_nosec
          %td
            = mute(res.schedule, "no recurrence") do
              = res.schedule.to_s
          %td= cutlong(res.description, 50)
          
  -@reservations.each do |res|
    = render partial: "modal", locals: {reservation: res, show_room: true}

app/views/reservations/show.html.haml
.page-header
  %h2
    = @reservation.summary
    %small=link_to @reservation.room.name, room_path(@reservation.room)
   
%table.table.table-bordered{style: "width: 50%"}
  %tbody
    %tr
      %td
        %strong Author
      %td
        = mute(@reservation.author) do
          = link_to @reservation.author.login, user_path(@reservation.author)
    %tr
      %td
        %strong Start
      %td= @reservation.start.to_s :date_time_nosec
    %tr
      %td
        %strong End
      %td= @reservation.end.to_s :date_time_nosec

%strong Description: 
%blockquote
  = mute(@reservation.description)
  
-if user_signed_in?
  .form-actions
    .btn-group
      = link_to glyph("cog") + " Edit", edit_room_reservation_path(@reservation.room, @reservation), class: "btn"
      = link_to glyph("remove") + " Delete", room_reservation_path(@reservation.room, @reservation), class: "btn btn-danger", "data-method" => "delete", "data-confirm" => "Are you sure?"
  
  