config/routes.rb
Reservoir::Application.routes.draw do
  
  get '/rooms/remote/calendar/update', :to => "rooms#start_remotecal_worker", :as => "remote_calendar_update"
  resources :rooms do
    get "/reservations/remote", :to => "reservations#index_remote"
    post "/reservations/deletemany", :to => "reservations#destroymany"
    get "/remote/calendar/update", :to => "rooms#start_remotecal_worker", :as => "remote_calendar_update"
    resources :reservations 
  end
 
  devise_for :users, controllers: { registrations: "registrations" }
  devise_scope :user  do
    get '/login', :to => 'devise/sessions#new', :as => "login"
    get '/register', :to => 'devise/registrations#new', :as => "register"
    get '/users/edit/password', :to => 'registrations#edit_password', :as => "user_password_change"
    get '/users/show/:id', :to => "registrations#show", :as => "user"   
  end

  get '/users/show/:id/reservations', :to => "reservations#indexByUser", :as => "user_reservations"
  get '/reservations/find', :to => "reservations#find"
  post '/reservations/find', :to => "reservations#search"
  post '/search', :to => "home#search", :as => "search"
  
  
  
  root :to => "home#index"

end

app/models/room.rb
class Room < ActiveRecord::Base
  has_many :reservations
  attr_accessible :capacity, :equipment, :location, :name, :cal_url
  attr_accessor :remote_last_updated

  validates :capacity , numericality: true
  validates :name, presence: true, length: { maximum: 100 }
  validate :validate_cal_url
  def validate_cal_url
    #TODO
  end

  def fetch_remote_calendar
    #download
    puts "Downloading files"
    unless(cal_url.empty?)
      require "net/http"

      uri = URI.parse(cal_url)
      http = Net::HTTP.new(uri.host, uri.port)
      http.use_ssl=true
      http.verify_mode = OpenSSL::SSL::VERIFY_NONE
      http.request_get(uri.path) do |res|
        body = res.body
        #workaround for RiCal bug #41
        body.gsub!(/;";/, ';')
        
        cal = RiCal.parse_string(body)
        store_cal(cal)
      end

    else
      clean_cal()
    end
  end

  private

  def convert_single_temp_reservation(event)
    res = TempReservation.new(summary: event.summary,
    description: event.description, start: Time.zone.at(event.start_time.to_i),
    end: Time.zone.at(event.finish_time.to_i))
    res.room = self

    #build schedule
    if(event.recurs?)
      res.schedule = IceCube::Schedule.new(res.start, end_time: res.end)
      
      event.rrule_property.each do |rrule|
        interval = rrule.interval
        interval = 1 unless(interval)
        # create rule by freq and interval
        case rrule.freq
        when "SECONDELY"; rule = IceCube::Rule.secondly(interval)
        when "MINUTELY"; rule = IceCube::Rule.minutely(interval)
        when "HOURLY"; rule = IceCube::Rule.hourly(interval)
        when "DAILY"; rule = IceCube::Rule.daily(interval)
        when "WEEKLY"; rule = IceCube::Rule.weekly(interval)
        when "MONTHLY"; rule = IceCube::Rule.monthly(interval)
        when "YEARLY"; rule = IceCube::Rule.yearly(interval)
        end

        #additional rec. limitation
        rrule.by_list.each do |name, value|
          case name
          when :bymonth; rule.month_of_year(*value)
          when :byday; parsebyday(rule, value)
          when :bymonthday; rule.day_of_month(*value.map(&:ordinal))
          when :byyearday; rule.day_of_year(*value.map(&:ordinal))
          when :byhour; rule.hour_of_day(*value)
          when :byminute; rule.minute_of_hour(*value)
          #:byweekno  is not implemented, has no impl. in ice_cube
          #:bysetpos; is not implemented, has no impl. in ice_cube    
          end
        end

        #recurrence limitation
        rule.until(rrule.until.to_datetime) if rrule.until
        rule.count(rrule.count.to_i) if rrule.count
          
          
        #add rrule
        res.schedule.add_recurrence_rule rule
      end
    end

    res
  end

  def parsebyday(rule, value)
    valueregex = /-?\d+\D+/
    if(value.first.to_s =~ valueregex)
      rule.day_of_week(to_days_range(value))
    else
      rule.day(*to_days(value))
    end
  end

  def to_days(values)
    values.map do |value|
      parse_day(value.to_s.match(/[a-zA-Z]+/)[0])
    end
  end

  def parse_day(day)
    case day
    when "MO"; :monday
    when "TU"; :tuesday
    when "WE"; :wednesday
    when "TH"; :thursday
    when "FR"; :friday
    when "SA"; :saturday
    when "SU"; :sunday
    end
  end

  #possible loss of data when merging hashes
  def to_days_range(values)
    values.map do |value|
      match = value.to_s.match(/(-?\d+)(\D+)/)
      { parse_day(match[2]) => [match[1].to_i] }
    end.reduce(&:merge)
  end

  def store_cal(cal)
    
    #convert to entities (model)
    puts "Converting to entities"
    entities = cal.first.events.map {|event| convert_single_temp_reservation(event)}
    
    ActiveRecord::Base.transaction do
      #delete old
      puts "Deleting old temps"
      TempReservation.of(self).delete_all

      #store current
      puts "Storing new temps #{cal.first.events.count}"
      entities.each {|entity| entity.save }

      ActiveRecord::Base.connection.execute("UPDATE temp_reservations SET description = '' WHERE description IS NULL")
      ActiveRecord::Base.connection.execute("UPDATE temp_reservations SET summary = '' WHERE summary IS NULL")
    end
  end


  def clean_cal
    puts "Deleting all temps"
    TempReservation.of(self).delete_all
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  
  before_filter :authenticate_user!, except: [:index, :show, :start_remotecal_worker]
  
  def index
    @rooms = Room.order("location ASC, name ASC")
    
    respond_to do |format|
      format.html
      format.json { render json: @rooms }
    end
  end
  
  def destroy
    room = Room.find(params[:id])
    
    #delete all reservations and temp-reservations
    room.reservations.destroy_all
    TempReservation.of(room).delete_all
    room.destroy
    
    redirect_to rooms_path
    flash[:info] = "Room #{room.name.html_safe} was deleted."
  end
  
  def new
    @room = Room.new
  end
  
  def create
    @room = Room.new(params[:room])
    if @room.save
      Delayed::Job.enqueue(RemoteCalendar.new(@room.id))
      flash[:info] = "Room #{@room.name.html_safe} was created."
      redirect_to @room
    else
      render action: "new"
    end
    
  end
  
  def edit
    @room = Room.find(params[:id])
  end
  
  def update
    @room = Room.find(params[:id])
    old_cal_url = @room.cal_url
    if(@room.update_attributes(params[:room]))
      if(old_cal_url != @room.cal_url)
        Delayed::Job.enqueue(RemoteCalendar.new(@room.id))
      end
      flash[:info] = "Room #{@room.name.html_safe} was updated."
      redirect_to @room
    else
      render action: "edit"
    end
  end
  
  def show
    @room = Room.find(params[:id])
    rnd_temp = TempReservation.of(@room).first
    @last_remote_update = (rnd_temp)? rnd_temp.updated_at.localtime : nil
 
    now = Time.zone.now
    reservations = Reservation.of(@room).between(now, now + 14.days).map(&:next_occurrence)
    reservations.concat(TempReservation.of(@room).between(now, now + 14.days).map(&:next_occurrence))
    reservations.delete_if { |el| el==nil } 
    @next_reservation = reservations.min_by(&:start)
    
    #new reservation for form
    @reservation = Reservation.new
    @reservation.start_string = Time.zone.now.localtime.to_s :date_time_nosec
    @reservation.end_string = (Time.zone.now.localtime + 30.minutes).to_s :date_time_nosec
    
     #pending jobs
    jobs = ActiveRecord::Base.connection.execute("SELECT * FROM delayed_jobs ORDER BY run_at")
    transform_jobs(jobs, @room.id)
   
   
    @update_jobs = jobs.select {|job| job["handler"].is_a? RemoteCalendar }
    @failed_jobs = jobs.select {|job| job["last_error"] != nil}
    
    @failed_ratio = 0
    @failed_ratio = @failed_jobs.size * 100 / (@update_jobs.size) if (@update_jobs.size) > 0
  
    respond_to do |format|
      format.html
      format.json { render json: @room }
    end
  end
  
  def start_remotecal_worker
    if(params[:room_id])
      Delayed::Job.enqueue(RemoteCalendar.new(params[:room_id], false))
      flash[:info] = "Remote calendar update was scheduled and will be finished soon."
      
      params[:id] = params[:room_id]
      redirect_to action: "show", id: params[:room_id]
      
    else
      Delayed::Job.enqueue(RemoteCalendar.new)

      flash[:info] = "Remote calendar update for all rooms was scheduled. "
      
      redirect_to action: "index"
    end

  end
  
  private
  def transform_jobs(jobs, room_id=nil)
    jobs.each {|job| job["handler"] = YAML.load(job["handler"])}
   
   if(room_id)
      #filter jobs by room_id
      jobs.keep_if { |job| job["handler"].room_id == room_id.to_s}
    end
  end
end

app/helpers/rooms_helper.rb
module RoomsHelper
  
  
  def status(next_reservation)
    if next_reservation
      if next_reservation.running? || next_reservation.start.localtime - 10.minutes <= Time.now
        content_tag(:span, 'Occupied', class: "label label-big label-important") + content_tag(:small, " #{next_reservation.summary}" + 
           " ends in #{time_diff_in_natural_language(Time.now, next_reservation.end.localtime)}")
      else
         content_tag(:span, 'Free', class: "label label-big label-success") + " #{next_reservation.summary}" + 
           " starts in #{time_diff_in_natural_language(Time.now, next_reservation.start.localtime)}"
      end
    else
      content_tag(:span, 'no event in the next 14 days', class: "muted")
    end
  end
  
  def time_diff_in_natural_language(from_time, to_time)
    from_time = from_time.to_time if from_time.respond_to?(:to_time)
    to_time = to_time.to_time if to_time.respond_to?(:to_time)
    distance_in_seconds = ((to_time - from_time).abs).round
    components = []
  
    %w(day hour minute).each do |interval|
      # For each interval type, if the amount of time remaining is greater than
      # one unit, calculate how many units fit into the remaining time.
      if distance_in_seconds >= 1.send(interval)
        delta = (distance_in_seconds / 1.send(interval)).floor
        distance_in_seconds -= delta.send(interval)
        components << pluralize(delta, interval)
      end
    end
  
    components.join(", ")
  end
  
end

app/views/rooms/_form.html.haml
-if @room.errors.any?
  .alert.alert-error.fade.in
    Some #{@room.errors.size==1? "error" : "errors"} occured, fix #{@room.errors.size==1? "it" : "them"} and try again.
  
= form_for(@room, html: {class: "form-horizontal"}) do |f|
  .control-group
    = f.label :name, class: "control-label"
    .controls
      = f.text_field :name, placeholder: "name"
      -unless @room.errors[:name].empty?
        %p.text-error-inline= @room.errors[:name].join(", ")
  .control-group
    = f.label :capacity, class: "control-label"
    .controls
      = f.text_field :capacity
      -unless @room.errors[:capacity].empty?
        %p.text-error-inline= @room.errors[:capacity].join(", ")
  .control-group
    = f.label :location, class:"control-label"
    .controls
      = f.text_field :location, placeholder: "location"
      -unless @room.errors[:location].empty?
        %p.text-error-inline= @room.errors[:location].join(", ")
  .control-group
    = f.label :equipment, class: "control-label"
    .controls
      = f.text_field :equipment, placeholder: "equipment"
      -unless @room.errors[:equipment].empty?
        %p.text-error-inline= @room.errors[:equipment].join(", ")
  .control-group
    = f.label :cal_url, "Calendar url", class: "control-label"
    .controls
      = f.text_field :cal_url, class: "input-long", placeholder: "url to calendar"
      -unless @room.errors[:cal_url].empty?
        %p.text-error-inline= @room.errors[:cal_url].join(", ")
          
  
  .form-actions
    = f.submit "Submit", class: "btn btn-primary"
    = link_to "Back", :back, class: "btn"

app/views/rooms/edit.html.haml
.page-header
  %h1 Edit room #{@room.name}
  
= render partial: "form"
    

app/views/rooms/index.html.haml
.page-header
  %h1 Rooms
 
-if @rooms.any?
  %table.table.table-striped.table-hover
    %thead
      %tr
        %th Name 
        %th Capacity
        %th Location
        %th Equipment
    %tbody
      - @rooms.each do |room|
        %tr
          %td= link_to room.name, room_path(room)
          %td
            %span.badge.badge-info= room.capacity
          %td= mute(room.location)
          %td= mute(room.equipment)
          %td
            -if user_signed_in?
              .btn-group
                = link_to content_tag(:span,'', class: "icon-cog") + " Edit", edit_room_path(room), class: "btn btn-small"
                = link_to content_tag(:span,'', class: "icon-remove") + " Delete", room_path(room), method: :delete, class: "btn btn-danger btn-small", data: {confirm: "Are you sure?"}
-else
  %p.lead No rooms, add some first
  

app/views/rooms/show.html.haml
-@sidelinks = {header: "Room detail", glyph("file") + "Basic information" => "#basic", glyph("comment") + "Reservations" => "#reservations", glyph("plus") + "Add reservation" => "#newreservation"}
-@spy = true
-content_for :script do
  :javascript
    var reservationsFeeds = ["#{room_reservations_path(@room)}.js", "#{room_reservations_remote_path(@room)}.js" ]
    
-if(@update_jobs.size) > 0
  -content_for :side_panel do
    .well.well-small.affix{style: "margin-top: 200px; width: 130px"}
      %ul.nav.nav-list
        %li.nav-header Planned jobs
        %li
          %table.table.table-condesed.table-bordered
            %tr
              %th{style: "text-align: center"}
                =glyph("refresh")
              %th{style: "text-align: center"}
                =glyph("warning-sign")
              %tr
                %td{style: "text-align: center"}
                  %p.text-info
                    = @update_jobs.size
                %td{style: "text-align: center"}
                  %p.text-error
                    = @failed_jobs.size
         
          
          .progress.progress-striped
            .bar.bar-info.active{style: "width: #{ 100 - @failed_ratio }%"}
            .bar.bar-danger{style: "width: #{ @failed_ratio }%"}

.hero-unit#basic
  %h1= @room.name
  %table.table.room-attributes
    %tbody
      %tr
        %td Capacity:
        %td
          %span.badge.badge-info.label-medium= @room.capacity
      %tr
        %td Location:
        %td= mute(@room.location)
      %tr
        %td Equipment:
        %td= mute(@room.equipment)
      %tr
        %td Status:
        %td= status(@next_reservation)
  -if user_signed_in?
    =link_to content_tag(:span, '', class: "icon-cog") + " Edit", edit_room_path(@room), class: "btn"
    =link_to content_tag(:span, '', class: "icon-remove") + " Delete", @room, method: :delete, class: "btn btn-danger", data: {confirm: "Are you sure?"}
  .pull-right
    -unless @room.cal_url.empty?
      -if @last_remote_update
        %span.muted
          Last remote update at 
          = @last_remote_update.to_s :date_time_nosec
      -else
        %span.muted
          Not updated yet 
      = link_to("Update now", room_remote_calendar_update_path(@room), class: "btn btn-info")
        
#reservations
  %h2 
    Reservations
    %small#loading (started)
  #calendar
    
#newreservation
  -if user_signed_in?
    %h2 Add reservation
    =render "reservations/form"
  -else
    %a{href: login_path}
      %h3.muted
        Log in first in order to create reservations
    
= render "reservations/modal"   
    
 
      