config/routes.rb
Reservoir::Application.routes.draw do
  
  get '/rooms/remote/calendar/update', :to => "rooms#start_remotecal_worker", :as => "remote_calendar_update"
  resources :rooms do
    get "/reservations/remote", :to => "reservations#index_remote"
    post "/reservations/deletemany", :to => "reservations#destroymany"
    get "/remote/calendar/update", :to => "rooms#start_remotecal_worker", :as => "remote_calendar_update"
    resources :reservations 
  end
 
  devise_for :users, controllers: { registrations: "registrations" }
  devise_scope :user  do
    get '/login', :to => 'devise/sessions#new', :as => "login"
    get '/register', :to => 'devise/registrations#new', :as => "register"
    get '/users/edit/password', :to => 'registrations#edit_password', :as => "user_password_change"
    get '/users/show/:id', :to => "registrations#show", :as => "user"   
  end

  get '/users/show/:id/reservations', :to => "reservations#indexByUser", :as => "user_reservations"
  get '/reservations/find', :to => "reservations#find"
  post '/reservations/find', :to => "reservations#search"
  post '/search', :to => "home#search", :as => "search"
  
  
  
  root :to => "home#index"

end

app/views/layouts/application.html.haml
!!! 5
%html(lang="en")
  %head
    %meta(charset="utf-8")
    %meta(http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1")
    %meta(name="viewport" content="width=device-width, initial-scale=1.0")
    %title= content_for?(:title) ? yield(:title) : "Reservoir"
    = csrf_meta_tags
    / Le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
      = javascript_include_tag "http://html5shim.googlecode.com/svn/trunk/html5.js"
    = stylesheet_link_tag "application", :media => "all"
    %link(href="images/apple-touch-icon-144x144.png" rel="apple-touch-icon-precomposed" sizes="144x144")
    %link(href="images/apple-touch-icon-114x114.png" rel="apple-touch-icon-precomposed" sizes="114x114")
    %link(href="images/apple-touch-icon-72x72.png" rel="apple-touch-icon-precomposed" sizes="72x72")
    %link(href="images/apple-touch-icon.png" rel="apple-touch-icon-precomposed")
    
    
    -if content_for?(:script)
      = yield(:script)
        
    :javascript
      var root_path = "#{ENV['RAILS_RELATIVE_URL_ROOT']}"

  
  %body{@spy? {"data-spy" => "scroll", "data-target" => "#sidebar" } : {}}
  
    .navbar.navbar-fixed-top
      .navbar-inner
        .container
          %a.btn.btn-navbar(data-target=".nav-collapse" data-toggle="collapse")
            %span.icon-bar
            %span.icon-bar
            %span.icon-bar
          %a.brand{href: "#", title: "go to the top"} Reservoir
          %a.brand{href: root_path}= glyph("home")
          .container.nav-collapse 
            %ul.nav
              %li{class: active_class(rooms_path) }= link_to(glyph("list") + " Rooms", rooms_path)
              -if user_signed_in?
                %li= link_to(glyph("plus") + " Add new room", new_room_path)
              %li= link_to(glyph("search") + " Find a reservation", reservations_find_path)              
                
             
            
            -if user_signed_in?
              .pull-right.btn-group
                %a.btn.btn-primary{ href: edit_user_registration_path}
                  %span.icon-user
                  %span.login= current_user.login
                %button.btn.btn-primary.dropdown-toggle{"data-toggle" => "dropdown"}
                  %span.caret
                %ul.dropdown-menu
                  %li= link_to content_tag(:span, "", class: "icon-list") + "Reservations", user_reservations_path(current_user)
                  %li.divider
                  %li= link_to content_tag(:span, '', class: "icon-key") + " Change password", user_password_change_path
                  %li= link_to content_tag(:span, "", class: "icon-off") + "Log out", destroy_user_session_path, method: :delete
                    
             
              
            -else
              = form_for("user", url: user_session_path, html: {class: "navbar-search pull-right form-inline"}) do |f|
                = f.text_field :login, class: "input-small", placeholder: "Login"
                = f.password_field :password, class: "input-small", placeholder: "Password"
                = f.check_box :remember_me
                = f.label :remember_me, class: "checkbox"
                = f.submit "Log in", class: "btn"
                = link_to "Register", register_path, class: "btn"
                
                
                
      
    .container

      .row
        .span10
          = bootstrap_flash
          = yield
        .span2
          -if @sidelinks
            .well.affix#sidebar
              %ul.nav.nav-list
                -if @sidelinks[:header]
                  %li.nav-header= @sidelinks[:header]
                -@sidelinks.each_pair do |name, link|
                  -next if name == :header
                  %li{class: active_class(link)}=link_to name, link
          -if content_for(:side_panel)
            = yield(:side_panel)                
                
               
           
           
    
    %footer
     
        
    /
      Javascripts
      \==================================================
    / Placed at the end of the document so the pages load faster
    = javascript_include_tag "application"

app/views/layouts/empty.html.haml
!!! 5
%html(lang="en")
  %head
    %meta(charset="utf-8")
    %meta(http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1")
    %meta(name="viewport" content="width=device-width, initial-scale=1.0")
    %title= content_for?(:title) ? yield(:title) : "Reservoir"
    = csrf_meta_tags
    / Le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
      = javascript_include_tag "http://html5shim.googlecode.com/svn/trunk/html5.js"
    = stylesheet_link_tag "application", :media => "all"
    %link(href="images/apple-touch-icon-144x144.png" rel="apple-touch-icon-precomposed" sizes="144x144")
    %link(href="images/apple-touch-icon-114x114.png" rel="apple-touch-icon-precomposed" sizes="114x114")
    %link(href="images/apple-touch-icon-72x72.png" rel="apple-touch-icon-precomposed" sizes="72x72")
    %link(href="images/apple-touch-icon.png" rel="apple-touch-icon-precomposed")
    
    :css
      body {
        background-color: #F5F5F5;
        padding-bottom: 40px;
        padding-top: 40px;
      }
      .form-signin {
        background-color: #FFFFFF;
        border: 1px solid #E5E5E5;
        border-radius: 5px 5px 5px 5px;
        box-shadow: 0 1px 2px rgba(0, 0, 0, 0.05);
        margin: 0 auto 20px;
        max-width: #{(@width? @width : "300")}px;
        padding: 19px 29px 29px;
        text-align: center;
      }
      .form-signin .form-signin-heading, .form-signin .checkbox {
        margin-bottom: 10px;
      }
      .form-signin input[type="text"], .form-signin input[type="password"], .form-signin input[type="email"] {
        font-size: 16px;
        height: 20px;
        margin-bottom: 15px;
        padding: 7px 9px;
      }
      .form-horizontal .control-label {
        width: 110px;
      }
      .form-horizontal .controls {
        margin-left: 120px;
      }
      .form-horizontal .form-actions {
        padding-left: 0px;
      }
      

  %body
    %div{style: "position:absolute; top: 10px; right: 10px;" }
      %a{href: root_path}
        = glyph("home", "large")
    %div{style: "position: absolute; top: 10px; left: 10px;" }
      = link_to glyph("arrow-left", "large"), :back
    .container
      = yield
    
    /
      Javascripts
      \==================================================
    / Placed at the end of the document so the pages load faster
    = javascript_include_tag "application"

app/views/layouts/wide.html.haml
!!! 5
%html(lang="en")
  %head
    %meta(charset="utf-8")
    %meta(http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1")
    %meta(name="viewport" content="width=device-width, initial-scale=1.0")
    %title= content_for?(:title) ? yield(:title) : "Reservoir"
    = csrf_meta_tags
    / Le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
      = javascript_include_tag "http://html5shim.googlecode.com/svn/trunk/html5.js"
    = stylesheet_link_tag "application", :media => "all"
    %link(href="images/apple-touch-icon-144x144.png" rel="apple-touch-icon-precomposed" sizes="144x144")
    %link(href="images/apple-touch-icon-114x114.png" rel="apple-touch-icon-precomposed" sizes="114x114")
    %link(href="images/apple-touch-icon-72x72.png" rel="apple-touch-icon-precomposed" sizes="72x72")
    %link(href="images/apple-touch-icon.png" rel="apple-touch-icon-precomposed")
    
    
    -if content_for?(:script)
      = yield(:script)
        
    :javascript
      var root_path = "#{ENV['RAILS_RELATIVE_URL_ROOT']}"

  
  %body{@spy? {"data-spy" => "scroll", "data-target" => "#sidebar" } : {}}
  
    .navbar.navbar-fixed-top
      .navbar-inner
        .container
          %a.btn.btn-navbar(data-target=".nav-collapse" data-toggle="collapse")
            %span.icon-bar
            %span.icon-bar
            %span.icon-bar
          %a.brand{href: "#", title: "go to the top"} Reservoir
          %a.brand{href: root_path}= glyph("home")
          .container.nav-collapse 
            %ul.nav
              %li{class: active_class(rooms_path) }= link_to(glyph("list") + " Rooms", rooms_path)
              -if user_signed_in?
                %li= link_to(glyph("plus") + " Add new room", new_room_path)
              %li= link_to(glyph("search") + " Find a reservation", reservations_find_path)              
                
             
            
            -if user_signed_in?
              .pull-right.btn-group
                %a.btn.btn-primary{ href: edit_user_registration_path}
                  %span.icon-user
                  %span.login= current_user.login
                %button.btn.btn-primary.dropdown-toggle{"data-toggle" => "dropdown"}
                  %span.caret
                %ul.dropdown-menu
                  %li= link_to content_tag(:span, "", class: "icon-list") + "Reservations", user_reservations_path(current_user)
                  %li.divider
                  %li= link_to content_tag(:span, '', class: "icon-key") + " Change password", user_password_change_path
                  %li= link_to content_tag(:span, "", class: "icon-off") + "Log out", destroy_user_session_path, method: :delete
                    
             
              
            -else
              = form_for("user", url: user_session_path, html: {class: "navbar-search pull-right form-inline"}) do |f|
                = f.text_field :login, class: "input-small", placeholder: "Login"
                = f.password_field :password, class: "input-small", placeholder: "Password"
                = f.check_box :remember_me
                = f.label :remember_me, class: "checkbox"
                = f.submit "Log in", class: "btn"
                = link_to "Register", register_path, class: "btn"
                
                
                
      
    .container

      .row
      
        = bootstrap_flash
        = yield
           
           
    
    %footer
     
        
    /
      Javascripts
      \==================================================
    / Placed at the end of the document so the pages load faster
    = javascript_include_tag "application"